PASSIVE_CURRENT = 2.5
ACTIVE_CURRENT = 13.25

DISCHARGE_THRESHOLD = 23.5
CHARGE_THRESHOLD = 25.0

TEMPERATURE_STATE_NUMBER = 10
IRRADIANCE_STATE_NUMBER = 20

BOT_ACTIVITY_BEGINNING = 6
BOT_ACTIVITY_FINISHING = 20